#!/usr/bin/env ruby
# frozen_string_literal: true

puts 'welcome to mgmt. building and installing...'

bld_res = `gem build ./sys-mgmt.gemspec`
puts bld_res.to_s
version = /(?<=Version\: )\d\.\d\.\d/.match bld_res

system "sudo gem install ./sys-mgmt-#{version[0]}.gem"
